/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calcu.h"

double *
suma_1_svc(op *argp, struct svc_req *rqstp)
{
	static double  result;
        result = argp->sumando1 + argp->sumando2;

	return &result;
}

double *
resta_1_svc(op *argp, struct svc_req *rqstp)
{
	static double  result;

	result = argp->sumando1 - argp->sumando2;

	return &result;
}

double *
multiplicacion_1_svc(op *argp, struct svc_req *rqstp)
{
	static double  result;

	result = argp->sumando1*argp->sumando2;

	return &result;
}

double *
division_1_svc(op *argp, struct svc_req *rqstp)
{
	static double  result;

	result = argp->sumando1/ argp->sumando2;

	return &result;
}
