/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calcu.h"


void
calcu_prog_1(char *host, int tipo, op  operacion)
{
	CLIENT *clnt;
	double  *result_1;
	op  suma_1_arg;
	double  *result_2;
	op  resta_1_arg;
	double  *result_3;
	op  multiplicacion_1_arg;
	double  *result_4;
	op  division_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, CALCU_PROG, CALCU_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	switch(tipo){
		case 1:
		 suma_1_arg=operacion;
		 result_1 = suma_1(&suma_1_arg, clnt);
		 if (result_1 == (double *) NULL) {
			clnt_perror (clnt, "call failed");
		 }
		 printf ("La suma de %i + %i = %f\n", suma_1_arg.sumando1, suma_1_arg.sumando2, *result_1);
	               break;
		case 2:
		 resta_1_arg=operacion;
		 result_2 = resta_1(&resta_1_arg, clnt);
		 if (result_2 == (double *) NULL) {
			clnt_perror (clnt, "call failed");
		 }
		 printf ("La resta de %i - %i = %f\n",resta_1_arg.sumando1, resta_1_arg.sumando2, *result_2);
			break;
		case 3:
		 multiplicacion_1_arg=operacion;
		 result_3 = multiplicacion_1(&multiplicacion_1_arg, clnt);
		 if (result_3 == (double *) NULL) {
			clnt_perror (clnt, "call failed");
		 }
		 printf ("La multiplicacion de %i * %i = %f\n",multiplicacion_1_arg.sumando1, multiplicacion_1_arg.sumando2, *result_3);
		 	break;
	
		case 4:
		 division_1_arg=operacion;
		 result_4 = division_1(&division_1_arg, clnt);
		 if (result_4 == (double *) NULL) {
			clnt_perror (clnt, "call failed");
		 }
		  printf ("La division de %i / %i = %f\n",division_1_arg.sumando1, division_1_arg.sumando2, *result_4);
		  break;
	default:
	printf ("Operacion no definida\n");
	break;
	}

#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;
	int tipo=atoi(argv[2]);
        op  oper;
	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	oper.sumando1=atoi(argv[3]);
	oper.sumando2=atoi(argv[4]);
	calcu_prog_1 (host, tipo,oper);
exit (0);
}
