/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _CALCU_H_RPCGEN
#define _CALCU_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct op {
	int sumando1;
	int sumando2;
};
typedef struct op op;

#define CALCU_PROG 0x31111111
#define CALCU_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define SUMA 1
extern  double * suma_1(op *, CLIENT *);
extern  double * suma_1_svc(op *, struct svc_req *);
#define RESTA 2
extern  double * resta_1(op *, CLIENT *);
extern  double * resta_1_svc(op *, struct svc_req *);
#define MULTIPLICACION 3
extern  double * multiplicacion_1(op *, CLIENT *);
extern  double * multiplicacion_1_svc(op *, struct svc_req *);
#define DIVISION 4
extern  double * division_1(op *, CLIENT *);
extern  double * division_1_svc(op *, struct svc_req *);
extern int calcu_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define SUMA 1
extern  double * suma_1();
extern  double * suma_1_svc();
#define RESTA 2
extern  double * resta_1();
extern  double * resta_1_svc();
#define MULTIPLICACION 3
extern  double * multiplicacion_1();
extern  double * multiplicacion_1_svc();
#define DIVISION 4
extern  double * division_1();
extern  double * division_1_svc();
extern int calcu_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_op (XDR *, op*);

#else /* K&R C */
extern bool_t xdr_op ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_CALCU_H_RPCGEN */
